### ISSUE TITLE
Replicator annotations clears out in the source secret

### ISSUE THREAD

**Issue by Shaileshgnaik** [mittwald/kubernetes-replicator#25]
The replicator annotation gets cleared in the source secret. 

Please find the attached logs for the replicator deployment.
[LogsIssue.txt](https://github.com/mittwald/kubernetes-replicator/files/3609700/LogsIssue.txt)

**Comment by harsha-kotni** [comment]
I am also facing a similar issue. The scenario is as follows :

I have a secret (default-cert-secret) in the default tenant with all the replicator annotations.
"annotations": {
                           "replicator.v1.mittwald.de/replication-allowed": "true",
                           "replicator.v1.mittwald.de/replication-allowed-namespaces": ".*"
                          }
Using Kubernetes SDK, I am creating a secret dynamically and this new secret has an annotation as  replicator.v1.mittwald.de/replicate-from : default/default-cert-secret

Initially it worked as expected but later on, I found that the annotations in secret of default namespace are getting removed. However, there is no pattern observed in this behavior. Sometimes the annotation gets removed after a day and sometimes it only takes an hour. Someone has to manually update the annotation in the default secret every now and then.

Could really appreciate some help from the team here. I don't see anything important in the logs as well. It is pretty much same as what @Shaileshgnaik  had attached.

Am I missing anything here or is this the expected behavior ??

@Shaileshgnaik Please let me know in case you find the reason behind this.

**Comment by martin-helmich** [comment]
Hey folks -- sorry for the late response on this one. I have no explanation for this issue -- at no point anywhere in the code do we patch or otherwise modify the _source_ secret. Is it possible that there's another controller working in your cluster working on these secrets (maybe a deployment that overrides the source secrets with `kubectl apply`, as was the issue in #40)?
