### ISSUE TITLE
Helm chart down?

### ISSUE THREAD

**Issue by michaelmohamed** [mittwald/kubernetes-replicator#328]
I am getting this error:
```
...Successfully got an update from the "bitnami" chart repository
...Unable to get an update from the "mittwald" chart repository (https://helm.mittwald.de):
	Get "https://helm.mittwald.de/index.yaml": dial tcp 178.16.59.30:443: connect: connection refused
````

**Comment by martin-helmich** [comment]
We've had some minor intermittent connectivity issues over the day; the timestamp from your report correlates with our logs. Apologies if this caused any inconvenience. In general, the Helm repo is (and will remain) up and running. 🙂 

Will close for now, as this issue is not directly related to this project.
