### ISSUE TITLE
Keys removed from source should be removed from dependent

### ISSUE THREAD

**Issue by jasminen** [mittwald/kubernetes-replicator#42]
Hi,
When a Key is removed from source secret, it is not removed from the replicated ones.

**Comment by martin-helmich** [comment]
You're absolutely right, good catch! :+1:

Unfortunately, this is a non-trivial fix, because we effectively _merge_ both target and source secret/configmap and don't really track which fields were replicated from the source in the first place. This means that we cannot differentiate which fields of a target secret originally belonged to the source.

To fix, we'd probably need a new annotation at the target secret that tracks which _fields_ were actually replicated from the source -- then, if one of those goes missing at the source, we could simply drop those.

Alternatively, we could simply drop _all_ keys from the target that are not present in the source secret (which -- now that I think of it -- would be consistent with the "on delete"-behaviour, which also indiscriminately clears everything from the target secret). Could be considered a breaking change, however,

I'll give this some more thought as soon as I find the time.

**Comment by jasminen** [comment]
I think the later is the right way to go (drop all keys from the target that are not present in the source secret). It can also be configurable of course if you think this change is too risky.

**Comment by martin-helmich** [comment]
I've decided to err on the side of caution for now and implemented #46, since it allows us to stay completely backwards-compatible. This change basically tracks the synchronized keys in a separate annotation. If, on subsequent synchronizations, one of these keys should be missing from the source secret, it will also be cleared from the target secret.
